### PR TITLE
Update Midseason 2023-A

### PR DESCRIPTION
**Pull request by EstebanMz**
- Track Rotation for 2023-A Season
**Tracks Removed:** Antigrav, DS Desert Hills, RC Stadium 1, RC Stadium 2, RV Temple, Spooktober SSS, The Reactor, Toys in the Night.
**Tracks Added:** Casino RV, Desolate District 1, Fairground 1, Fairground 2, Home 2, Subway, School 1 (THUG), White Rose Chapel.

- Desolate District 1 includes fixes to its AI Nodes, Triggers and INF File.
Added more nodes on straights to mitigate bad repos in the track.
Adjustments to track direction triggers on reverse version.
FOV increased and Reverse Start modified.

- Subway 2 updated to version 1.2.

### CODE REVIEW

**Comment by BGMP** [comment]
I'll review this later tonight

**Comment by EstebanMz** [comment]
More fixes at Disolate District 1 to its AI nodes, Objects, POS nodes and Triggers.

**Comment by EstebanMz** [comment]
Out: Subway
In: Conduciendo Fumado (RVA)

**Review by Y100XTT — APPROVED** [review]

**Review by BGMP — APPROVED** [review]
:shipit:

**Pull request merged**
