### PR TITLE
RVA Track Pack Season 2023-2

### PR DESCRIPTION
**Pull request by EstebanMz**
**Tracklist:**
Airport 1
Botanical Garden EX
Calaboq
Cardboard Castle
Casino RV
Castle 1
Castle 2
Desolate District 1
Downtown 1
Downtown 2
Fairground 1
Fairground 2
Game Room 1
Game Room 2
Grisville
Helios/Lunar
Home 1
Home 2
Hospital 1
Hospital 2
Jailhouse Rock
Junkyard 2
Market Mayhem
Medieval: Redux
Metro-Volt
Moon Dawn
Museum 3
Mysterious Toy-Volt Factory 1
Mysterious Toy-Volt Factory 2
PetroVolt
Port Limano 2
Port Limano EX
Quake!
Rooftop Chase: Redux
Rooftops 1
Sakura
Santorini
School’s Out! 1
School’s Out! 2
Skating Toys Redux
Spa-Volt 1
Spa-Volt 2
StadVolt
Subway 2
Toy World Mayhem
User-Deli: XL
Venice

Note: This version includes Improved AI nodes released for the stock tracks at the moment (10 out of 14 tracks)

### CODE REVIEW

**Comment by EstebanMz** [comment]
**More context about the new pack release:**
- Based on the [results](https://cdn.discordapp.com/attachments/711270352256499772/1143304035366092840/rva_tracks_final_results.png) of the track survey done on our Discord server.
- At last minute I've choosen to replace The Great Silence with the new release by Paperman: [Cardboard Castle](https://www.revoltworld.net/dl/cardboard-castle/).
- Track versions are up-to-date with their available versions on Re-Volt World website.
- Improved AI nodes mods for the stock tracks have been included in the pack.
- This pack shares most of its tracks with I/O's Track Pack (v23.0303), for that reason, I've created a tiny version of the pack which only includes the files not available at Re-Volt I/O Pack. More info on the Readme.

**Comment by BGMP** [comment]
Hey there. Thanks for putting all of this together into one PR. I'll review it when I get back home!

**Review by BGMP — CHANGES_REQUESTED** [review]
> Note: This version includes Improved AI nodes released for the stock tracks at the moment (10 out of 14 tracks)

If these are not currently included in RVGL itself, then I'd say it's better not to include them ourselves. Whenever RVGL or its assets are updated, then everyone will receive these at the same time.

However, if these AI node improvements are not meant for RVGL itself, then I don't think RVA's pack is the way to go about distributing them.

Let me know what you think, though.

> At last minute I've choosen to replace The Great Silence with the new release by Paperman: [Cardboard Castle](https://www.revoltworld.net/dl/cardboard-castle/).

Why was this a last minute decision? Was there a tie or something when voting for each track?

**Comment by EstebanMz** [comment]
> If these are not currently included in RVGL itself, then I'd say it's better not to include them ourselves. Whenever RVGL or its assets are updated, then everyone will receive these at the same time.

I've been thinking that RVA would be good place to try them out and give a real-scenario feedback in case there's a chance that such modifications end up being distributed with RVGL itself in the future.

> Why was this a last minute decision? Was there a tie or something when voting for each track?

Actually yes, I've posted the results above so you can check it by yourself, but honestly this track I'm suggesting has nothing do to with the track survey. Cardboard Castle was released weeks later after the track survey ended, and after it catched the interest of some regular players, and myself included, I've decided to give it a chance in the pack, Cardboard would replace one of the tracks with the lowest amount of votes.
There isn't really a deep reason for my decision rather than my interest to see how will be its impact in the pack and in multiplayer races, and if it's a negative impact then I'll roll back my decision.

**Comment by BGMP** [comment]
>>> Improved AI nodes mods for the stock tracks have been included in the pack.

>> If these are not currently included in RVGL itself, then I'd say it's better not to include them ourselves. Whenever RVGL or its assets are updated, then everyone will receive these at the same time.

> I've been thinking that RVA would be good place to try them out and give a real-scenario feedback in case there's a chance that such modifications end up being distributed with RVGL itself in the future.

I'd like to read @Y100XTT 's opinion here. I've quoted the relevant conversation for context.

> Actually yes, I've posted the results above so you can check it by yourself, but honestly this track I'm suggesting has nothing do to with the track survey. Cardboard Castle was released weeks later after the track survey ended, and after it catched the interest of some regular players, and myself included, I've decided to give it a chance in the pack, Cardboard would replace one of the tracks with the lowest amount of votes.
There isn't really a deep reason for my decision rather than my interest to see how will be its impact in the pack and in multiplayer races, and if it's a negative impact then I'll roll back my decision.

OK. Let's give it a try!

**Comment by Y100XTT** [comment]
> I've been thinking that RVA would be good place to try them out and give a real-scenario feedback in case there's a chance that such modifications end up being distributed with RVGL itself in the future.

I don't think we should include the track mods either. For consistency among players I'd recommend to keep the stock content files identical to the original game's and the RVGL assets. _Also there being mods for only 10 of the 14 tracks (so far) makes it somewhat of a WIP modification, too._ I'd rather let the RVGL devs review these (once all mods are out) and then consider including them to the game or not.

> Cardboard Castle was released weeks later after the track survey ended, and after it catched the interest of some regular players, and myself included, I've decided to give it a chance in the pack, Cardboard would replace one of the tracks with the lowest amount of votes.

This is fine in my opinion. Let's see what feedback will the players give to the track as it is played.

**Review by BGMP — CHANGES_REQUESTED** [review]
Hey, @EstebanMz, 

So, generally speaking, I'd say let's pass on the new AI nodes for now, and let's go ahead with Cardboard Castle.

Thanks again for taking the time to put all of this together 📦

**Comment by EstebanMz** [comment]
I've followed your suggestions, without further ado, I'm gonna merge this pull request right now.

**Pull request merged**
