### PR TITLE
Pack Update May 2023

### PR DESCRIPTION
**Pull request by EstebanMz**
The following tracks have been updated:
- Botanical Garden EX
- Hospital 2
- Skating Toys Redux
- Subway 2

### CODE REVIEW

**Comment by EstebanMz** [comment]
Hospital 2 has been updated too.

**Review by BGMP — COMMENTED** [review]
Why "(1)" ? Is this part of another PR?

**Comment by EstebanMz** [comment]
> Why "(1)" ? Is this part of another PR?

Just in case I'd need to do a hotfix.

**Comment by BGMP** [comment]
> > Why "(1)" ? Is this part of another PR?
> 
> Just in case I'd need to do a hotfix.

In that case just make a different PR or push changes to this one. It's easier to review that way.

I'll get to checking all the changes shortly.

**Comment by EstebanMz** [comment]
File updated:
- skatoysred.w

**Comment by BGMP** [comment]
Since you're adding more stuff progressively, request another review from me when you're done please.

Thanks for taking care of the update, esteban :shipit:

**Comment by EstebanMz** [comment]
I don't think it's needed as this would be the last one. It was the blinking tag before the entry of the forest park.

**Review by Y100XTT — APPROVED** [review]

**Review by BGMP — APPROVED** [review]
Thanks for putting this together as always!

**Pull request merged**
