### PR TITLE
Season 2024-A Pack Update

### PR DESCRIPTION
**Pull request by EstebanMz**
**Changes**
- Added 24 new tracks: 24 new tracks added: Aqueduct, Elementary 1, Elementary 2, Forest Mansion 2, HMS Invincible, Holiday Camp: California Edition, Hull Breach 3000 (RVA), Kadish Sprint, Library, MineZcraft, Motel in the Hood, Museum EX, Museum Unleashed (RVA), Paper Town 1, Port Limano 1, Ranch, Rigs Highway, RV Temple (RVA), Spring Visit, The Great Silence, Toys in the Hood 4 (RVA), ToySoldierz, White Rose Chapel, Wladyslawowo.
- Removed 5 tracks: Castle 1, Junkyard 2, Medieval Redux, Mysterious Toy-Volt Factory 1, Mysterious Toy-Volt Factory 2.

### CODE REVIEW

**Comment by BGMP** [comment]
Could you ask @Y100XTT to take a look and leave a review? I probably won't be in until the 8th-9th

**Comment by EstebanMz** [comment]
I doubt I'll send more updates until the weekend, but sure!

**Comment by EstebanMz** [comment]
I forgot to mention that we still have to wait for the results of the lego contest, and if there aren't enough tracks to make a decision to include them, then one custom track has to be added as there is still one spot anyways.

**Review by Y100XTT — APPROVED** [review]

**Review by BGMP — APPROVED** [review]
Thanks for putting this together @EstebanMz , and thanks @Y100XTT for reviewing it too

**Pull request merged**
