### PR TITLE
Add ToySoldierz 2024 and Remove Ranch

### PR DESCRIPTION
**Pull request by EstebanMz**
I'm quoting the message I left at suggestions' channel on our Discord server, which had 10 upvotes (including myself):

### Replace Ranch with ToySoldierz 2024
- Custom surface properties make the track worse.
- Old computers struggle to keep up the framerate, more noticeable at reversed mode.
- Not the most exiting race line because the visual references actually take you to the wrong way half of the time.
- In favor of ToySoldierz 2024, its feeling is so different compared to ToySoldierz (Original) that both tracks wouldn't confict in the pack.

### CODE REVIEW

**Comment by BGMP** [comment]
@EstebanMz Should I review this or is it a draft?

**Comment by EstebanMz** [comment]
Yes, it's already good for review @BGMP

**Review by BGMP — APPROVED** [review]
Alright @EstebanMz , sorry about the long wait. Please add ToySoldierz 2024 to https://github.com/Re-Volt-America/tracks.rva.lat if it isn't there already.

Apart from that, this looks good

**Comment by EstebanMz** [comment]
@BGMP don't worry about being late to approve this PR, I've yet to fix a bunch of bugs on some tracks and also we have planned to replace some cars in the pack that didn't work well, more details later when I finish testing them.
It'd be fine if we can pull out the pack updates in 2-3 weeks, before the start of 3rd Ranking.

**Pull request merged**
